# Generated by Django 5.1.7 on 2025-04-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_cc_fast_delete_cc_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['nome_job'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_stream',
        ),
        migrations.RemoveField(
            model_name='job',
            name='workstation',
        ),
        migrations.AddField(
            model_name='job',
            name='criticidade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Criticidade'),
        ),
        migrations.AddField(
            model_name='job',
            name='estacao_trabalho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estação de Trabalho'),
        ),
        migrations.AddField(
            model_name='job',
            name='horario_ativacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horário de Ativação'),
        ),
        migrations.AddField(
            model_name='job',
            name='nome_job',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsavel_primario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Primário'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsavel_secundario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Secundário'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsavel_terciario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Terciário'),
        ),
        migrations.AddField(
            model_name='job',
            name='stream_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='job',
            name='aplicacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplicação'),
        ),
    ]
