# Generated by Django 5.1.7 on 2025-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_cc_fast_delete_cc_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em Progresso', 'Em Progresso'), ('Concluído', 'Concluído'), ('Falha', 'Falha')], default='Aguardando', max_length=20),
        ),
    ]
