# Generated by Django 5.1.7 on 2025-04-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_delete_cc_fast_delete_cc_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['job_name'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='aplicacao',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_stream',
        ),
        migrations.AddField(
            model_name='job',
            name='application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplicação'),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='job',
            name='primary_responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Primário'),
        ),
        migrations.AddField(
            model_name='job',
            name='secondary_responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Secundário'),
        ),
        migrations.AddField(
            model_name='job',
            name='stream',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stream'),
        ),
        migrations.AddField(
            model_name='job',
            name='tertiary_responsible',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Terciário'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='workstation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estação de Trabalho'),
        ),
    ]
