# Generated by Django 5.1.7 on 2025-04-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_options_remove_job_aplicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='stream',
            new_name='job_stream',
        ),
    ]
