# Generated by Django 5.1.7 on 2025-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Real de Retorno'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='movement_docs/', verbose_name='Documento/Comprovante'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
