# Generated by Django 5.1.7 on 2025-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_inventory_alter_hardware_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.IntegerField(default=1, verbose_name='Quantidade Mínima'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Unitário'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da Garantia'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('available', 'Disponível'), ('in_use', 'Em Uso'), ('maintenance', 'Em Manutenção'), ('reserved', 'Reservado'), ('discontinued', 'Descontinuado')], default='available', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
