# Generated by Django 5.1.7 on 2025-03-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_inventorymovement_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='document_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='new_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='old_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('moved', 'Movido'), ('maintenance', 'Em Manutenção'), ('returned', 'Retornado'), ('deleted', 'Deletado')], max_length=50),
        ),
    ]
