# Generated by Django 5.1.7 on 2025-03-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_inventoryhistory_details_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
    ]
