# Generated by Django 5.1.7 on 2025-03-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_inventory_minimum_quantity_inventory_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Última Manutenção'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='maintenance_interval',
            field=models.IntegerField(default=180, verbose_name='Intervalo de Manutenção (dias)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], default='low', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('old_quantity', models.IntegerField(null=True)),
                ('new_quantity', models.IntegerField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hardware.inventory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Inventário',
                'verbose_name_plural': 'Históricos de Inventário',
                'ordering': ['-created_at'],
            },
        ),
    ]
