# Generated by Django 5.1.7 on 2025-03-25 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_inventory_barcode_inventory_last_maintenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_location', models.CharField(max_length=255, verbose_name='Localização Anterior')),
                ('current_location', models.CharField(max_length=255, verbose_name='Nova Localização')),
                ('moved_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='hardware.inventory', verbose_name='Item')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Movido por')),
            ],
            options={
                'verbose_name': 'Movimentação de Inventário',
                'verbose_name_plural': 'Movimentações de Inventário',
                'ordering': ['-moved_at'],
            },
        ),
    ]
