# Generated by Django 5.1.7 on 2025-04-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_delete_inventorymovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='priority',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='low', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('reservado', 'Reservado'), ('descontinuado', 'Descontinuado'), ('pendente', 'Pendente')], default='available', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='action',
            field=models.CharField(choices=[('criado', 'Criado'), ('atualizado', 'Atualizado'), ('movido', 'Movido'), ('manutencao', 'Em Manutenção'), ('retornado', 'Retornado'), ('deletado', 'Deletado')], max_length=50),
        ),
    ]
